apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mc-pvcstore-wg
provisioner: mumblecluster.io/mc-pvcstore-wg
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - vers=4.2
