apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-canary-pod-config
  namespace: app-desk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mc-pvcstore-wg
  resources:
    requests:
      storage: 1Gi
